name: Server logs
on:
    workflow_dispatch:

jobs:

  build:
    name: View Logs
    runs-on: ubuntu-latest
    steps:
    - name: Get the logs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
            cd /webapps/college_cupid_backend
            docker-compose -f docker-compose.prod.yml logs --tail=1000
