# This is a basic workflow that is manually triggered

name: Deploy Test Server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
      branches:
      - "dev2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Establish ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
            cd /webapps/test-servers/college_cupid_backend
            sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
            sudo chmod g+rwx "$HOME/.docker" -R
            git checkout dev
            git fetch
            git pull
            docker compose -f docker-compose.dev.yml up -d --build
